version: '2.1'
services:
    mtls-ambassador:
        build: .
        ports:
            - ${MTLS_PORT-8080}:8080
        volumes:
            - ${MTLS_CERT:-./certs/server/server.crt}:/etc/mtls/certs/server/server.crt
            - ${MTLS_KEY:-./certs/server/server.key}:/etc/mtls/certs/server/server.key
        environment:
            MTLS_MENDER_USER: "mtls@mender.io"
            MTLS_MENDER_PASS: "correcthorsebatterystaple"
            MTLS_MENDER_BACKEND: "https://staging.hosted.mender.io"
            MTLS_DEBUG_LOG: "true"
            MTLS_INSECURE_SKIP_VERIFY: "true"
