apiVersion: v1
kind: Service
metadata:
  name: mtls-ping-service
  labels:
    app: mtls-ping
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
    service.beta.kubernetes.io/aws-load-balancer-internal: "false"
spec:
  selector:
    app: mtls-ping
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer
  externalTrafficPolicy: Local
