apiVersion: v1
kind: Service
metadata:
  name: mtls-ping-service
  labels:
    app: mtls-ping
spec:
  selector:
    app: mtls-ping
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer
