// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// Client is an autogenerated mock type for the Client type
type Client struct {
	mock.Mock
}

// Login provides a mock function with given fields: ctx, user, pwd
func (_m *Client) Login(ctx context.Context, user string, pwd string) (string, error) {
	ret := _m.Called(ctx, user, pwd)

	var r0 string
	if rf, ok := ret.Get(0).(func(context.Context, string, string) string); ok {
		r0 = rf(ctx, user, pwd)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, user, pwd)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Preauth provides a mock function with given fields: ctx, idData, pubKey, userToken
func (_m *Client) Preauth(ctx context.Context, idData string, pubKey string, userToken string) error {
	ret := _m.Called(ctx, idData, pubKey, userToken)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) error); ok {
		r0 = rf(ctx, idData, pubKey, userToken)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
