// Copyright 2020 Northern.tech AS
//
//    All Rights Reserved

// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	http "net/http"

	mock "github.com/stretchr/testify/mock"
)

// Proxy is an autogenerated mock type for the Proxy type
type Proxy struct {
	mock.Mock
}

// Redirect provides a mock function with given fields: w, r
func (_m *Proxy) Redirect(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}
